spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;REFERENTIAL_INTEGRITY=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: com.edison.project.domain.bubble.H2TestDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  sql:
    init:
      mode: never
AWS_ACCESS_KEY: dummy-access-key
AWS_SECRET_KEY: dummy-secret-key

cloud:
  aws:
    credentials:
      access-key: dummy-access-key
      secret-key: dummy-secret-key